version: '3.8'

services:
  atrac-api:
    image: mdencoder:latest
    container_name: atrac-api
    environment:
      - LOG_LEVEL=
    volumes:
      - /data/atrac-api/uploads:/uploads
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
